### ISSUE TITLE
PoolParty requirements

### ISSUE THREAD

**Issue by dw8547** [devinit/devdatawarehouse#14]
Find out the minimum/required server specifications for PoolParty.
Try: http://www.poolparty.biz/.

**Comment by dw8547** [comment]
PoolParty system requirements:
https://grips.semantic-web.at/display/public/POOLDOKU/PoolParty+System+Requirements

PoolParty client requirements:
https://grips.semantic-web.at/display/public/POOLDOKU/PoolParty+Client+Requirements

Requirements overview (https://grips.semantic-web.at/pages/viewpage.action?pageId=40437810):
PoolParty needs a Linux (Debian 6, CentOS 5 or 6, Red Hat Enterprise Linux 5 or 6, Ubuntu 10.04 LTS) or Windows Server 2008 R2, Java 5 or 6 and Tomcat 5 or 6. 
The more RAM, the better, but at least 4 GB should be available. 
Mozilla Firefox is required to use the administration part of the thesaurus management, any other browser is good for the end-user interfaces.

**Comment by bill-anderson** [comment]
8GB RAM recommended
