### ISSUE TITLE
DELL XPS-15-9530 screen malfunction

### ISSUE THREAD

**Issue by dw8547** [devinit/devdatawarehouse#56]
Horizontal lines on screen have reappeared following the screen repair on 31/07/2015. Possible hardware malfunction?

**Comment by dw8547** [comment]
They have now disappeared, but the source of the problem is still unknown.

**Comment by leightonjames** [comment]
Hey @dw8547 
Please keep an eye on this and let me know if the issue returns. If it does, I'll get onto Dell ts.
Thanks

**Comment by dw8547** [comment]
@leightonjames, the screen on the DELL XPS-15-9530 is malfunctioning in the same manner as before (horizontal, not flickering for now, lines have appeared on the screen).

**Comment by dw8547** [comment]
@leightonjames, I have attached a picture of the screen malfunction.
![20151030_092639](https://cloud.githubusercontent.com/assets/10259585/10842361/f013846a-7ee8-11e5-966e-1f1748c8d36c.jpg)

**Comment by cmanley** [comment]
It looks a lot like mine:
http://en.community.dell.com/support-forums/laptop/f/3519/t/19665889
I'm sure it's a recurring problem due to poor hardware design.
