### ISSUE TITLE
Install and configure PostgreSQL on the server

### ISSUE THREAD

**Issue by dw8547** [devinit/devdatawarehouse#7]
Install PostgreSQL.
Configure PostgreSQL.

**Comment by bill-anderson** [comment]
I will sort out finance for brainfurnace

**Comment by dw8547** [comment]
Installed:

# Object relational SQL database server, version 9.3
postgresql-9.3

# Debug symbols for PostgreSQL 9.3
postgresql-9.3-dbg

# Frontend programs for PostgreSQL 9.3
postgresql-client-9.3

# Additional facilities for PostgreSQL 9.3
postgresql-contrib-9.3

# PL/Perl procedural language for PostgreSQL 9.3
postgresql-plperl-9.3

# PL/Python procedural language for PostgreSQL 9.3
postgresql-plpython-9.3

# Graphical administration tool for PostgreSQL
pgadmin3

# Graphical administration tool for PostgreSQL, documentation
pgadmin3-data

# Graphical administration tool for PostgreSQL, debugging symbols
pgadmin3-dbg

# Web based administration tool for PostgreSQL
phppgadmin

# Python module for PostgreSQL
python-psycopg2

# Python module for PostgreSQL, documentation package
python-psycopg2-doc

# Python module for PostgreSQL, debug extension
python-psycopg-dbg

# PostgreSQL module for Python
python-pygresql

# PostgreSQL module for Python
python-pygresql-dbg
